settings:
  title: 'Service Status Page'
  url: 'https://service-status.vidal.life' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.'
    url: 'https://workers.cloudflare.com/'
    method: GET 
    expectStatus: 200 
    followRedirect: false
    linkable: false

  - id: www-portalcomb-cat
    name: PortalCoMB
    description: 'Portal CoMB.'
    url: 'https://www.portalcomb.cat'
    method: GET
    expectStatus: 200
    linkable: true
